test test

diff --git a/.github/workflows/backend.main.yml b/.github/workflows/backend.main.yml
--- a/.github/workflows/backend.main.yml
+++ b/.github/workflows/backend.main.yml
@@ -10,9 +10,23 @@ jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - uses: azure/login@v1
-        with:
-        client-id: ${{ secrets.AZURE_CLIENT_ID }}
-        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+    - uses: actions/checkout@v3
+    - uses: azure/login@v1
+      with:
+      client-id: ${{ secrets.AZURE_CLIENT_ID }}
+      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+
+    - name: Check frontend directory
+      run: |
+        if [ ! -d "frontend" ]; then
+          echo "Frontend directory not found!"
+          exit 1
+        fi
+        echo "Frontend directory exists, proceeding with deployment..."
+
+    - name: Upload to blob storage
+      uses: azure/CLI@v1
+      with:
+        inlineScript: |
+          az storage blob upload-batch --account-name nkazureresumestorageweb --auth-mode key -d '$web' -s ./frontend --overwrite
