test2

diff --git a/.github/workflows/backend.main.yml b/.github/workflows/backend.main.yml
--- a/.github/workflows/backend.main.yml
+++ b/.github/workflows/backend.main.yml
@@ -1,5 +1,7 @@
-name: Run Azure Login with OIDC
-on: [push]
+name: New frontend worflow
+on: branch: [main]
+  paths:
+    - "frontend/**"
 
 permissions:
   id-token: write
@@ -15,9 +17,10 @@ jobs:
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
-      - name: Azure CLI script
-        uses: azure/cli@v2
-        with:
-          azcliversion: latest
-          inlineScript: |
-            az account show
+      - name: Check frontend directory
+        run: |
+          if [ ! -d "./frontend" ]; then
+            echo "Frontend directory not found!"
+            exit 1
+          fi
+          echo "Frontend directory exists, proceeding with deployment..."
